security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      user_checker: security.user_checker
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 604800
        path:     /
      form_login:
        provider: app_user_provider
        csrf_token_generator: security.csrf.token_manager
      logout:       true

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/scraper, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/profile/, role: ROLE_USER }